---
title: "WSJ Data Analysis with BERT embedding"
author: "Yingying Fan, Jinchi Lv, Ao Sun and Yurou Wang"
output:
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
params:
  target_var: "CPIAUCSL"
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


source("./utility.R")
library(lubridate)
library(jsonlite)


Average_prediction <- function(y, H) {
  sapply(seq_len(H), function(h) mean(tail(y, h)))
}

check_coverage <- function(interval_row, true_val) {
  as.integer(true_val >= interval_row[1] & true_val <= interval_row[2])
}

load_nf_metric <- function(index_name, h, model_name, results_dir = "./nf_results") {
  path <- file.path(results_dir, sprintf("%s_h%d.json", index_name, h))
  if (!file.exists(path)) {
    return(list(rmse = NA_real_, sign_mismatch = NA_real_))
  }
  payload <- fromJSON(path, simplifyVector = TRUE)
  if (!model_name %in% names(payload$results)) {
    return(list(rmse = NA_real_, sign_mismatch = NA_real_))
  }
  list(
    rmse = payload$results[[model_name]]$rmse,
    sign_mismatch = payload$results[[model_name]]$sign_mismatch
  )
}
```


```{r}
target_var <- params$target_var
macro_raw <- read.csv("./2025-10-MD.csv", stringsAsFactors = FALSE, check.names = FALSE)
macro_raw$sasdate <- suppressWarnings(as.Date(macro_raw[[1]], format = "%m/%d/%Y"))
macro_raw <- macro_raw[!is.na(macro_raw$sasdate), ]

bert_df <- read.csv("./wsj_mean_inflation_predictions_withBERT_vector.csv", stringsAsFactors = FALSE)

unrate_series <- macro_raw[, c("sasdate", "UNRATE")]
unrate_series <- unrate_series[!is.na(unrate_series$sasdate), ]

unrate_by_date <- function(dates, series_dates, series_vals) {
  ptr <- 1
  current <- NA_real_
  out <- numeric(length(dates))
  for (i in seq_along(dates)) {
    t_d <- dates[i]
    while (ptr <= length(series_dates) && series_dates[ptr] <= t_d) {
      current <- series_vals[ptr]
      ptr <- ptr + 1
    }
    out[i] <- current
  }
  out
}

df <- bert_df %>%
  mutate(date = as.Date(date)) %>%
  filter(date < as.Date("2025-09-01"), date > as.Date("2015-08-31")) %>%
  arrange(date) %>%
  mutate(
    month = format(date, "%Y-%m"),
    day = day(date),
    period = case_when(
      day <= 10 ~ "up",
      day <= 20 ~ "middle",
      TRUE ~ "down"
    ),
    UNRATE = unrate_by_date(date, unrate_series$sasdate, unrate_series$UNRATE)
  )
```


```{r}
df_summary <- df %>%
  group_by(month, period) %>%
  summarise(across(everything(), \(x) mean(x, na.rm = TRUE)), .groups = "drop")

y_m_list <- sort(unique(df_summary$month))
month_dates <- as.Date(paste0(y_m_list, "-01"))

tilde_y_m <- matrix(ncol = 3, nrow = length(y_m_list))
for (i in seq_along(y_m_list)) {
  res_ym <- y_m_list[i]
  tilde_y_m[i, ] <- df_summary[df_summary$month == res_ym, ]$pred_score
}


topic_cols <- names(df_summary)[grepl("^cls_\\d+$", names(df_summary))]
X_m <- matrix(ncol = length(topic_cols), nrow = length(y_m_list))
for (i in seq_along(y_m_list)) {
  res_ym <- y_m_list[i]
  X_m[i, ] <- apply(df_summary[df_summary$month == res_ym, topic_cols], 2, mean)
}
X_m <- scale(X_m)
colnames(X_m) <- topic_cols

topic_dates <- df$date
topic_months <- df$month
unrate_monthly <- df %>%
  group_by(month) %>%
  summarise(unrate = mean(UNRATE, na.rm = TRUE), .groups = "drop") %>%
  filter(month %in% y_m_list)
unem <- scale(unrate_monthly$unrate)
has_unem <- TRUE

m_dates <- macro_raw$sasdate
if (!target_var %in% names(macro_raw)) {
  stop(paste("Target variable not found in 2025-10-MD.csv:", target_var))
}
m_vals <- macro_raw[[target_var]]
ptr <- 1
current <- NA_real_
target_series <- numeric(length(topic_dates))
for (i in seq_along(topic_dates)) {
  t_d <- topic_dates[i]
  while (ptr <= length(m_dates) && m_dates[ptr] <= t_d) {
    current <- m_vals[ptr]
    ptr <- ptr + 1
  }
  target_series[i] <- current
}

y_df <- data.frame(month = topic_months, y = target_series) %>%
  group_by(month) %>%
  summarise(y = mean(y, na.rm = TRUE), .groups = "drop") %>%
  filter(month %in% y_m_list)
y_raw <- y_df$y
y_ratio <- c(1, y_raw[-1] / y_raw[-length(y_raw)])
y_center <- mean(y_ratio, na.rm = TRUE)
y_scale <- sd(y_ratio, na.rm = TRUE)
y <- (y_ratio - y_center) / y_scale
```




```{r}

EOD <- max(which(month_dates < as.Date("2024-06-01")))
sel <- select_topics(y, X_m, train_idx = 1:EOD, use_cor = FALSE, penalty_w = 10)
strong_idx <- match(sel$selected, colnames(X_m))
strong_idx <- strong_idx[!is.na(strong_idx)]
if (length(strong_idx) == 0) {
  strong_idx <- 1
}
strong_idx
```



```{r}
h_pred <- seq(8,15,1)

Res_m <- matrix(nrow = length(h_pred), ncol = 20)
for(k in seq_along(h_pred)){
  h <- h_pred[k]
  res_c <- NULL
  test_idx <- (length(y) - h + 1):length(y)
  obs_idx <- setdiff(seq_along(y), test_idx)


  ar_base <- auto.arima(y[obs_idx],max.q = 0, D = 0,seasonal = FALSE, allowmean = FALSE, allowdrift = FALSE)
  p1 <- max(1, ar_base$arma[1])
  ar_fit <- arima(y[obs_idx], order = c(p1,0,0), include.mean = FALSE)
  ar_prediction <- predict(ar_fit, n.ahead = h)$pred
  res_c <- c(res_c, sqrt(mean((ar_prediction-y[test_idx])^2)))
  res_c <- c(res_c, mean(sign(ar_prediction) !=sign(y[test_idx])))


  mean_prediction <- rep(y[max(obs_idx)], length(test_idx))
 res_c <- c(res_c, sqrt(mean((mean_prediction-y[test_idx])^2)))
  res_c <- c(res_c, mean(sign(mean_prediction) !=sign(y[test_idx])))


  ave_prediction <- Average_prediction(y[obs_idx], length(test_idx))
  res_c <- c(res_c, sqrt(mean((ave_prediction-y[test_idx])^2)))
  res_c <- c(res_c, mean(sign(ave_prediction) !=sign(y[test_idx])))


  ar_unem_base <- auto.arima(y[obs_idx], xreg = unem[obs_idx], max.q = 0, D = 0,seasonal = FALSE, allowmean = FALSE,      allowdrift = FALSE)
  p1_un <- max(1, ar_unem_base$arma[1])
  ar_unem_fit <- arima(y[obs_idx], xreg = unem[obs_idx], order = c(p1_un,0,0), include.mean = FALSE)
  ar_unem_prediction <- predict(ar_unem_fit, newxreg = unem[test_idx], n.ahead = h)$pred

  res_c <- c(res_c, sqrt(mean((ar_unem_prediction-y[test_idx])^2)))
  res_c <- c(res_c, mean(sign(ar_unem_prediction) !=sign(y[test_idx])))


  arx_fit <- arima(y[obs_idx], order = c(p1,0,0), xreg = X_m[obs_idx,strong_idx, drop = FALSE], include.mean = FALSE)
  arx_predictions <- predict(arx_fit, n.ahead = h, newxreg = X_m[test_idx,strong_idx, drop = FALSE])$pred

  res_c <- c(res_c, sqrt(mean((arx_predictions-y[test_idx])^2)))
  res_c <- c(res_c, mean(sign(arx_predictions) !=sign(y[test_idx])))


  arx_unem_fit <- arima(y[obs_idx],order = c(p1,0,0), xreg = cbind(X_m[obs_idx,strong_idx, drop=FALSE],unem[obs_idx]), include.mean = FALSE)
  arx_unem_predictions <- predict(arx_unem_fit, n.ahead=h, newxreg=cbind(X_m[test_idx,strong_idx,drop=FALSE],  unem[test_idx]))$pred

  res_c <- c(res_c, sqrt(mean((arx_unem_predictions-y[test_idx])^2)))
  res_c <- c(res_c, mean(sign(arx_unem_predictions) !=sign(y[test_idx])))


  p2=1

  powered_prediction <- LLM_TS.Predict(X_m, y, tilde_y_m, p1, p2, obs_idx, test_idx, strong_idx, h)

  res_c <- c(res_c, sqrt(mean((powered_prediction-y[test_idx])^2)))
  res_c <- c(res_c, mean(sign(powered_prediction) !=sign(y[test_idx])))


  powered_unem_prediction <- LLM_TS.Predict(cbind(X_m,unem), y, tilde_y_m, p1, p2, obs_idx, test_idx,
                                            c(strong_idx,ncol(X_m)+1), h)


  res_c <- c(res_c, sqrt(mean((powered_unem_prediction-y[test_idx])^2)))
  res_c <- c(res_c, mean(sign(powered_unem_prediction) !=sign(y[test_idx])))


  time_llm_metrics <- load_nf_metric(target_var, h, "TimeLLM")
  res_c <- c(res_c, time_llm_metrics$rmse, time_llm_metrics$sign_mismatch)


  patch_tst_metrics <- load_nf_metric(target_var, h, "PatchTST")
  res_c <- c(res_c, patch_tst_metrics$rmse, patch_tst_metrics$sign_mismatch)
  Res_m[k,] <- res_c
}
```

```{r}
BERT_mse <- Res_m[,seq(1, ncol(Res_m), 2)]
BERT_sign <- Res_m[,seq(2, ncol(Res_m), 2)]
colnames(BERT_mse) <- c('AR','RW','AVE','AR+unem','BERT','BERT+unem','LLM+BERT','LLM+BERT+unem',
                       'TimeLLM','PatchTST')
colnames(BERT_sign) <- c('AR','RW','AVE','AR+unem','BERT','BERT+unem','LLM+BERT','LLM+BERT+unem',
                        'TimeLLM','PatchTST')
```




```{r}
h_pi <- seq(8,15,1)

source("./SPI.R")

coverage_m <- matrix(NA, nrow = length(h_pi), ncol = 10)
len_m <- matrix(NA, nrow = length(h_pi), ncol = 10)

for(k in seq_along(h_pi)){
  h <- h_pi[k]

  test_idx <- (length(y) - h + 1):length(y)
  obs_idx <- setdiff(seq_along(y), test_idx)


  ar_base <- auto.arima(y[obs_idx], max.q = 0, D = 0, seasonal = FALSE, allowmean = FALSE, allowdrift = FALSE)
  p1 <- max(1, ar_base$arma[1])
  ar_fit <- Arima(y[obs_idx], order = c(p1,0,0),include.mean = FALSE)
  ar_predictions_fit <- forecast(ar_fit, h = length(test_idx))
  ar_interval <- cbind(ar_predictions_fit$lower[,2], ar_predictions_fit$upper[,2])
  len_m[k, 1] <- mean(as.numeric(ar_interval[,2] - ar_interval[,1]))
  coverage_m[k,1] <- mean(mapply(check_coverage, split(ar_interval, row(ar_interval)), y[test_idx]))


  if (has_unem) {
    ar_unem_fit <- Arima(y[obs_idx], order = c(p1,0,0), xreg = unem[obs_idx], include.mean = FALSE)
    ar_unem_predictions_fit <- forecast(ar_unem_fit, h = length(test_idx), xreg = unem[test_idx])
    ar_unem_interval <- cbind(ar_unem_predictions_fit$lower[,2], ar_unem_predictions_fit$upper[,2])
    len_m[k, 2] <- mean(as.numeric(ar_unem_interval[,2] - ar_unem_interval[,1]))
    coverage_m[k,2] <- mean(mapply(check_coverage, split(ar_unem_interval, row(ar_unem_interval)), y[test_idx]))
  } else {
    len_m[k,2] <- NA
    coverage_m[k,2] <- NA
  }





  arx_lda_fit <- Arima(y[obs_idx], order = c(p1,0,0), xreg = X_m[obs_idx,strong_idx,drop = FALSE], include.mean = FALSE)
  arx_lda_predictions_fit <- forecast(arx_lda_fit, h = length(test_idx), xreg = X_m[test_idx,strong_idx,drop = FALSE])
  arx_lda_interval <- cbind(arx_lda_predictions_fit$lower[,2], arx_lda_predictions_fit$upper[,2])

  len_m[k,3] <- mean(arx_lda_interval[,2] - arx_lda_interval[,1])
  coverage_m[k,3] <- mean(mapply(check_coverage, split(arx_lda_interval, row(arx_lda_interval)), y[test_idx]))


  if (has_unem) {
    arx_lda_un_fit <- Arima(y[obs_idx], order = c(p1,0,0), xreg = cbind(X_m[obs_idx,strong_idx, drop=FALSE], unem[obs_idx]), include.mean = FALSE)
    arx_lda_un_predictions_fit <- forecast(arx_lda_un_fit, h = length(test_idx), xreg = cbind(X_m[test_idx,strong_idx,drop=FALSE], unem[test_idx]))
    arx_lda_un_interval <- cbind(arx_lda_un_predictions_fit$lower[,2], arx_lda_un_predictions_fit$upper[,2])

    len_m[k,4] <- mean(arx_lda_un_interval[,2] - arx_lda_un_interval[,1])
    coverage_m[k,4] <- mean(mapply(check_coverage, split(arx_lda_un_interval, row(arx_lda_un_interval)), y[test_idx]))
  } else {
    len_m[k,4] <- NA
    coverage_m[k,4] <- NA
  }


  p1=ar_base$arma[1]
  p2=1
  powered_lda_res <- LLM_TS.BJ(X_m, y, tilde_y_m, p1, p2, obs_idx, test_idx, strong_idx, h)
  powered_lda_interval <- powered_lda_res$interval
  len_m[k,5] <- mean(powered_lda_interval[,2] - powered_lda_interval[,1])
  coverage_m[k,5] <- mean(mapply(check_coverage, split(powered_lda_interval, row(powered_lda_interval)), y[test_idx]))


  boot_lda_res <- LLM_TS.BOOT(X_m, y, tilde_y_m, p1, p2, obs_idx, test_idx, strong_idx, h, B = 500)
  boot_lda_interval <- boot_lda_res$interval
  len_m[k,6] <- mean(boot_lda_interval[,2] - boot_lda_interval[,1])
  coverage_m[k,6] <- mean(mapply(check_coverage, split(boot_lda_interval, row(boot_lda_interval)), y[test_idx]))



  if (has_unem) {
    powered_res <- LLM_TS.BJ(cbind(X_m,unem), y, tilde_y_m, p1, p2, obs_idx, test_idx,
                              c(strong_idx,ncol(X_m)+1), h)
    powered_interval <- powered_res$interval
    len_m[k,7] <- mean(powered_interval[,2] - powered_interval[,1])
    coverage_m[k,7] <- mean(mapply(check_coverage, split(powered_interval, row(powered_interval)), y[test_idx]))
  } else {
    len_m[k,7] <- NA
    coverage_m[k,7] <- NA
  }



  if (has_unem) {
    boot_res <- LLM_TS.BOOT(cbind(X_m,unem), y, tilde_y_m, p1, p2, obs_idx, test_idx,
                            c(strong_idx,ncol(X_m)+1), h, B = 500)
    boot_interval <- boot_res$interval
    len_m[k,8] <- mean(boot_interval[,2] - boot_interval[,1])
    coverage_m[k,8] <- mean(mapply(check_coverage, split(boot_interval, row(boot_interval)), y[test_idx]))
  } else {
    len_m[k,8] <- NA
    coverage_m[k,8] <- NA
  }
}

```

```{r}
spi_res <- spi_multi_horizon(
  y = y,
  X_m = X_m,
  tilde_y_m = tilde_y_m,
  strong_idx = strong_idx,
  h_vec = h_pi,
  unem = unem,
  has_unem = has_unem,
  cal_frac = 0.3,
  alpha = 0.05,
  p2 = 1
)

coverage_m[,9] <- spi_res$coverage_without_unem
len_m[,9] <- spi_res$length_without_unem
coverage_m[,10] <- spi_res$coverage_with_unem
len_m[,10] <- spi_res$length_with_unem
```

```{r}
BERT_cov <- coverage_m
colnames(BERT_cov) <- c('AR','AR+unem','BERT', 'BERT+unem', 'LLM+BERT(BJ)','LLM+BERT(Boot)','LLM+BERT+unem(BJ)','LLM+BERT+unem(Boot)','LLM+BERT(SPI)','LLM+BERT+unem(SPI)')
BERT_len <- len_m
colnames(BERT_len) <- c('AR','AR+unem','BERT', 'BERT+unem', 'LLM+BERT(BJ)','LLM+BERT(Boot)','LLM+BERT+unem(BJ)','LLM+BERT+unem(Boot)','LLM+BERT(SPI)','LLM+BERT+unem(SPI)')
```




```{r}
MSE_without_unem <- BERT_mse[,c('AR','RW','AVE','BERT','LLM+BERT','TimeLLM','PatchTST')]
rMSE_without_unem <- sweep(MSE_without_unem, 1, MSE_without_unem[,'AR',drop=FALSE], "/")
rMSE_without_unem <- cbind(h_pred, rMSE_without_unem)
knitr::kable(rMSE_without_unem,col.names = c('H','AR','RW','AVE','BERT','LLM+BERT','TimeLLM','PatchTST'), digits = 3, caption = 'Cumulative rPMSE without unemployment rate')
colMeans(rMSE_without_unem[,-1, drop = FALSE])
```



```{r}
Sign_without_unem <- BERT_sign[,c('AR','RW','AVE','BERT','LLM+BERT','TimeLLM','PatchTST')]
rSign_without_unem <- sweep(Sign_without_unem, 1, Sign_without_unem[,'AR',drop=FALSE], "/")
rSign_without_unem <- cbind(h_pred, rSign_without_unem)
knitr::kable(rSign_without_unem,col.names = c('H','AR','RW','AVE','BERT','LLM+BERT','TimeLLM','PatchTST'), digits = 3, caption = 'Cumulative rSign without unemployment rate')
colMeans(rSign_without_unem[,-1, drop = FALSE])
```


```{r}
MSE_with_unem <- BERT_mse[,c('AR+unem','RW','AVE','BERT+unem','LLM+BERT+unem')]
rMSE_with_unem <- sweep(MSE_with_unem, 1, MSE_with_unem[,'AR+unem',drop=FALSE], "/")
rMSE_with_unem <- cbind(h_pred, rMSE_with_unem)
knitr::kable(rMSE_with_unem,col.names = c('H','AR+unem','RW','AVE','BERT+unem','LLM+BERT+unem'), digits = 3, caption = 'Cumulative rPMSE with unemployment rate')
colMeans(rMSE_with_unem[,-1, drop = FALSE])
```


```{r}
Sign_with_unem <- BERT_sign[,c('AR+unem','RW','AVE','BERT+unem','LLM+BERT+unem')]
rSign_with_unem <- sweep(Sign_with_unem, 1, Sign_with_unem[,'AR+unem',drop=FALSE], "/")
rSign_with_unem <- cbind(h_pred, rSign_with_unem)
knitr::kable(rSign_with_unem,col.names = c('H','AR+unem','RW','AVE','BERT+unem','LLM+BERT+unem'), digits = 3, caption = 'Cumulative rSign with unemployment rate')
colMeans(rSign_with_unem[,-1, drop = FALSE])
```





```{r}
Cov_without_unem <- BERT_cov[,c('AR','BERT','LLM+BERT(BJ)','LLM+BERT(Boot)','LLM+BERT(SPI)')]
Cov_without_unem <- cbind(h_pi, Cov_without_unem)
knitr::kable(Cov_without_unem, col.names = c('H','AR','BERT','LLM+BERT(BJ)','LLM+BERT(Boot)','LLM+BERT(SPI)'), digits = 3, caption = 'Coverage rate without unemployment rate')
colMeans(Cov_without_unem[,-1, drop = FALSE], na.rm = TRUE)
```


```{r}
Len_without_unem <- BERT_len[,c('AR','BERT','LLM+BERT(BJ)','LLM+BERT(Boot)','LLM+BERT(SPI)')]
Len_without_unem <- cbind(h_pi, Len_without_unem)
knitr::kable(Len_without_unem, col.names = c('H','AR','BERT','LLM+BERT(BJ)','LLM+BERT(Boot)','LLM+BERT(SPI)'), digits = 3, caption = 'Interval length without unemployment rate')
colMeans(Len_without_unem[,-1, drop = FALSE], na.rm = TRUE)
```


```{r}
Cov_with_unem <- BERT_cov[,c('AR+unem','BERT+unem','LLM+BERT+unem(BJ)','LLM+BERT+unem(Boot)','LLM+BERT+unem(SPI)')]
Cov_with_unem <- cbind(h_pi, Cov_with_unem)
knitr::kable(Cov_with_unem, col.names = c('H','AR+unem','BERT+unem','LLM+BERT+unem(BJ)','LLM+BERT+unem(Boot)','LLM+BERT+unem(SPI)'), digits = 3, caption = 'Coverage rate with unemployment rate')
colMeans(Cov_with_unem[,-1, drop = FALSE], na.rm = TRUE)
```

```{r}
Len_with_unem <- BERT_len[,c('AR+unem','BERT+unem','LLM+BERT+unem(BJ)','LLM+BERT+unem(Boot)','LLM+BERT+unem(SPI)')]
Len_with_unem <- cbind(h_pi, Len_with_unem)
knitr::kable(Len_with_unem, col.names = c('H','AR+unem','BERT+unem','LLM+BERT+unem(BJ)','LLM+BERT+unem(Boot)','LLM+BERT+unem(SPI)'), digits = 3, caption = 'Interval length with unemployment rate')
colMeans(Len_with_unem[,-1, drop = FALSE], na.rm = TRUE)
```
